### ISSUE TITLE
Stderr:/bin/bash: /opt/resource/out.sh: Permission denied

### ISSUE THREAD

**Issue by steinbrueckri** [novas0x2a/concourse-jenkins-resource#1]
Hello,
i have try to start with your example and get this error.

![build-blocking__1_-_concourse](https://user-images.githubusercontent.com/578303/36717375-26f64efa-1b9e-11e8-91b5-7a14639fe53a.png)

regards Richard

**Comment by brentdemark** [comment]
Ran into the same thing.  I submitted a pull request to address this.

**Comment by steinbrueckri** [comment]
👍
